version: "3.7"

services:
  server:
    image: syncthing/syncthing:1.29.5@sha256:1914deddb3be7808579f3ce0eb4a1c493daa2f01e8953c2d73ba52ee2b1b418a
    restart: on-failure
    stop_grace_period: 1m
    hostname: umbrel-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/var/syncthing
    network_mode: host
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp