services:
  server:
    image: ghcr.io/tasmoadmin/tasmoadmin:v4.2.3@sha256:a2221d7c322073f9785e57d1e153419fe8702550fa7de92f47da7e3d85b92119
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    ports:
      - 8036:80