services:
  server:
    image: ghcr.io/tasmoadmin/tasmoadmin:v4.3.0@sha256:9e18fc87a061b5f0eb78d0f255e98815a61959a4e1c5d8706a7537e047930ea1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    ports:
      - 8036:80