services:
  server:
    image: ghcr.io/tasmoadmin/tasmoadmin:v4.2.1@sha256:f3e64d6e180ff39a2e1c6ca4e16976fd71d0558c972e8e549d01245ce6e2aa66
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/data
    ports:
      - 8036:80